services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp # build artifacts
    environment:
      - GIN_MODE=release # or debug
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  node_modules:
